# Generated by Django 6.0.1 on 2026-02-12 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_access_granted', models.BooleanField(default=False, verbose_name='Email Access Granted')),
                ('last_processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Processed Date')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ('user',),
            },
        ),
    ]
