# Generated by Django 6.0.1 on 2026-02-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user',), 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
