# Generated by Django 6.0.1 on 2026-02-12 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Message ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('sender', models.CharField(max_length=255, verbose_name='Sender')),
                ('received_date', models.DateTimeField(verbose_name='Received Date')),
                ('raw_email_body', models.TextField(verbose_name='Raw Email Body')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Parsed Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['user', '-received_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Subscription ID')),
                ('platform_name', models.CharField(max_length=255, verbose_name='Platform Name')),
                ('service_name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('already_canceled', models.BooleanField(default=False, verbose_name='Already Canceled')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Method')),
                ('unsubscribe_link', models.TextField(blank=True, null=True, verbose_name='Unsubscribe Link')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email_message_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='subscriptions.emailmessage', verbose_name='Email Message ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['user', '-end_date', '-start_date', 'platform_name', 'service_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'platform_name', 'service_name', 'start_date', 'end_date'), name='unique_user_platform_service_date')],
            },
        ),
    ]
