# Generated by Django 6.0.1 on 2026-02-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Is Trial'),
        ),
    ]
