# Generated by Django 6.0.1 on 2026-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_message_id',
            field=models.CharField(default='', max_length=32, verbose_name='Gmail Message ID'),
        ),
    ]
