# Generated by Django 6.0.1 on 2026-03-22 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_is_trial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_message_id',
            field=models.CharField(default=1, max_length=32, verbose_name='Gmail Message ID'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('user', 'gmail_message_id'), name='unique_user_gmail_message_id'),
        ),
    ]
