# Generated by Django 6.0.1 on 2026-02-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_unique_user_platform_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='already_canceled',
            field=models.BooleanField(default=False, verbose_name='Already Canceled'),
        ),
    ]
