# Generated by Django 6.0.1 on 2026-04-11 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_emailmessage_gmail_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('user', 'gmail_message_id'), name='unique_user_gmail_message_id'),
        ),
    ]
