# Generated by Django 6.0.1 on 2026-02-01 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_email_delete_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, verbose_name='Message ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('sender', models.CharField(max_length=255, verbose_name='Sender')),
                ('received_date', models.DateTimeField(verbose_name='Received Date')),
                ('raw_email_body', models.TextField(verbose_name='Raw Email Body')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Parsed Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
