# Generated by Django 6.0.1 on 2026-02-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_email_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['user', '-received_date'], 'verbose_name': 'Email Message', 'verbose_name_plural': 'Email Messages'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['user', '-end_date', '-start_date', 'platform_name', 'service_name'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
